[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "mido>=1.3.3",
    "music21>=9.7.1",
    "pretty-midi>=0.2.10",
    "scipy>=1.15.3",
]
